name: 'datathon_NWHL'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - ipykernel=6.26.0
  - matplotlib=3.8.2
  - pandas=2.1.3
  - ipython=8.17.2
  - pytest=7.4.3
  - vl-convert-python=1.1.0 
  - scipy=1.11.3 
  - myst-nb=0.17.2 
  - pip=23.1.2
  - nb_conda_kernels=2.3.1
  - numpy=1.25.2
  - jupyterlab
